# Copyright 2021 Wechat Group, Tencent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfcc_runtime/proto/operations/fusion.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="tfcc_runtime/proto/operations/fusion.proto",
    package="tfcc.runtime.operations.fusion",
    syntax="proto3",
    serialized_pb=_b(
        '\n*tfcc_runtime/proto/operations/fusion.proto\x12\x1etfcc.runtime.operations.fusion"\xa5\x01\n\x12\x46usionOpFixedShape\x12?\n\x08op_types\x18\x01 \x03(\x0e\x32-.tfcc.runtime.operations.fusion.OperationType\x12\x14\n\x0cresult_shape\x18\x02 \x03(\r\x12\x17\n\x0f\x62roadcast_marks\x18\x03 \x03(\x08"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01"x\n\x14\x46usionOpDynamicShape\x12?\n\x08op_types\x18\x01 \x03(\x0e\x32-.tfcc.runtime.operations.fusion.OperationType"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01*\x93\x03\n\rOperationType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x07\n\x03SUB\x10\x01\x12\x07\n\x03MUL\x10\x02\x12\x07\n\x03\x44IV\x10\x03\x12\x07\n\x03\x41\x42S\x10\x04\x12\x07\n\x03MIN\x10\x05\x12\x07\n\x03MAX\x10\x06\x12\x07\n\x03NEG\x10\x07\x12\x08\n\x04SQRT\x10\x08\x12\t\n\x05RSQRT\x10\t\x12\x08\n\x04RELU\x10\n\x12\x08\n\x04TANH\x10\x0b\x12\r\n\tLEAKYRELU\x10\x0c\x12\x07\n\x03LOG\x10\r\x12\x0b\n\x07SIGMOID\x10\x0e\x12\x0c\n\x08SOFTPLUS\x10\x0f\x12\x0e\n\nRECIPROCAL\x10\x10\x12\x08\n\x04\x43LIP\x10\x11\x12\x0e\n\x08REPEATED\x10\xc0\x84=\x12\r\n\x07PARAM_0\x10\x80\x89z\x12\r\n\x07PARAM_1\x10\x81\x89z\x12\r\n\x07PARAM_2\x10\x82\x89z\x12\r\n\x07PARAM_3\x10\x83\x89z\x12\r\n\x07PARAM_4\x10\x84\x89z\x12\r\n\x07PARAM_5\x10\x85\x89z\x12\r\n\x07PARAM_6\x10\x86\x89z\x12\r\n\x07PARAM_7\x10\x87\x89z\x12\r\n\x07PARAM_8\x10\x88\x89z\x12\r\n\x07PARAM_9\x10\x89\x89z\x12\x0e\n\x08PARAM_10\x10\x8a\x89z\x12\x0e\n\x08PARAM_11\x10\x8b\x89zb\x06proto3'
    ),
)

_OPERATIONTYPE = _descriptor.EnumDescriptor(
    name="OperationType",
    full_name="tfcc.runtime.operations.fusion.OperationType",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="ADD", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="SUB", index=1, number=1, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="MUL", index=2, number=2, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="DIV", index=3, number=3, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="ABS", index=4, number=4, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="MIN", index=5, number=5, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="MAX", index=6, number=6, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="NEG", index=7, number=7, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="SQRT", index=8, number=8, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="RSQRT", index=9, number=9, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="RELU", index=10, number=10, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="TANH", index=11, number=11, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="LEAKYRELU", index=12, number=12, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="LOG", index=13, number=13, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="SIGMOID", index=14, number=14, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="SOFTPLUS", index=15, number=15, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="RECIPROCAL", index=16, number=16, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="CLIP", index=17, number=17, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="REPEATED", index=18, number=1000000, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_0", index=19, number=2000000, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_1", index=20, number=2000001, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_2", index=21, number=2000002, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_3", index=22, number=2000003, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_4", index=23, number=2000004, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_5", index=24, number=2000005, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_6", index=25, number=2000006, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_7", index=26, number=2000007, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_8", index=27, number=2000008, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_9", index=28, number=2000009, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_10", index=29, number=2000010, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="PARAM_11", index=30, number=2000011, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=369,
    serialized_end=772,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONTYPE)

OperationType = enum_type_wrapper.EnumTypeWrapper(_OPERATIONTYPE)
ADD = 0
SUB = 1
MUL = 2
DIV = 3
ABS = 4
MIN = 5
MAX = 6
NEG = 7
SQRT = 8
RSQRT = 9
RELU = 10
TANH = 11
LEAKYRELU = 12
LOG = 13
SIGMOID = 14
SOFTPLUS = 15
RECIPROCAL = 16
CLIP = 17
REPEATED = 1000000
PARAM_0 = 2000000
PARAM_1 = 2000001
PARAM_2 = 2000002
PARAM_3 = 2000003
PARAM_4 = 2000004
PARAM_5 = 2000005
PARAM_6 = 2000006
PARAM_7 = 2000007
PARAM_8 = 2000008
PARAM_9 = 2000009
PARAM_10 = 2000010
PARAM_11 = 2000011


_FUSIONOPFIXEDSHAPE_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.fusion.FusionOpFixedShape.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=213,
    serialized_end=244,
)
_sym_db.RegisterEnumDescriptor(_FUSIONOPFIXEDSHAPE_VERSION)

_FUSIONOPDYNAMICSHAPE_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.fusion.FusionOpDynamicShape.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=213,
    serialized_end=244,
)
_sym_db.RegisterEnumDescriptor(_FUSIONOPDYNAMICSHAPE_VERSION)


_FUSIONOPFIXEDSHAPE = _descriptor.Descriptor(
    name="FusionOpFixedShape",
    full_name="tfcc.runtime.operations.fusion.FusionOpFixedShape",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="op_types",
            full_name="tfcc.runtime.operations.fusion.FusionOpFixedShape.op_types",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="result_shape",
            full_name="tfcc.runtime.operations.fusion.FusionOpFixedShape.result_shape",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="broadcast_marks",
            full_name="tfcc.runtime.operations.fusion.FusionOpFixedShape.broadcast_marks",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _FUSIONOPFIXEDSHAPE_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=79,
    serialized_end=244,
)


_FUSIONOPDYNAMICSHAPE = _descriptor.Descriptor(
    name="FusionOpDynamicShape",
    full_name="tfcc.runtime.operations.fusion.FusionOpDynamicShape",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="op_types",
            full_name="tfcc.runtime.operations.fusion.FusionOpDynamicShape.op_types",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _FUSIONOPDYNAMICSHAPE_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=246,
    serialized_end=366,
)

_FUSIONOPFIXEDSHAPE.fields_by_name["op_types"].enum_type = _OPERATIONTYPE
_FUSIONOPFIXEDSHAPE_VERSION.containing_type = _FUSIONOPFIXEDSHAPE
_FUSIONOPDYNAMICSHAPE.fields_by_name["op_types"].enum_type = _OPERATIONTYPE
_FUSIONOPDYNAMICSHAPE_VERSION.containing_type = _FUSIONOPDYNAMICSHAPE
DESCRIPTOR.message_types_by_name["FusionOpFixedShape"] = _FUSIONOPFIXEDSHAPE
DESCRIPTOR.message_types_by_name["FusionOpDynamicShape"] = _FUSIONOPDYNAMICSHAPE
DESCRIPTOR.enum_types_by_name["OperationType"] = _OPERATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FusionOpFixedShape = _reflection.GeneratedProtocolMessageType(
    "FusionOpFixedShape",
    (_message.Message,),
    dict(
        DESCRIPTOR=_FUSIONOPFIXEDSHAPE,
        __module__="tfcc_runtime.proto.operations.fusion_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.fusion.FusionOpFixedShape)
    ),
)
_sym_db.RegisterMessage(FusionOpFixedShape)

FusionOpDynamicShape = _reflection.GeneratedProtocolMessageType(
    "FusionOpDynamicShape",
    (_message.Message,),
    dict(
        DESCRIPTOR=_FUSIONOPDYNAMICSHAPE,
        __module__="tfcc_runtime.proto.operations.fusion_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.fusion.FusionOpDynamicShape)
    ),
)
_sym_db.RegisterMessage(FusionOpDynamicShape)


# @@protoc_insertion_point(module_scope)
