# Copyright 2021 Wechat Group, Tencent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfcc_runtime/proto/operations/relation.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="tfcc_runtime/proto/operations/relation.proto",
    package="tfcc.runtime.operations.relation",
    syntax="proto3",
    serialized_pb=_b(
        '\n,tfcc_runtime/proto/operations/relation.proto\x12 tfcc.runtime.operations.relation"(\n\x05\x45qual"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01"\'\n\x04Less"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01".\n\x0bLessOrEqual"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01"*\n\x07Greater"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01"1\n\x0eGreaterOrEqual"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01"&\n\x03Not"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01"*\n\x07UnEqual"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01\x62\x06proto3'
    ),
)


_EQUAL_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.relation.Equal.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=91,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_EQUAL_VERSION)

_LESS_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.relation.Less.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=91,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_LESS_VERSION)

_LESSOREQUAL_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.relation.LessOrEqual.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=91,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_LESSOREQUAL_VERSION)

_GREATER_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.relation.Greater.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=91,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_GREATER_VERSION)

_GREATEROREQUAL_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.relation.GreaterOrEqual.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=91,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_GREATEROREQUAL_VERSION)

_NOT_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.relation.Not.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=91,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_NOT_VERSION)

_UNEQUAL_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.relation.UnEqual.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=91,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_UNEQUAL_VERSION)


_EQUAL = _descriptor.Descriptor(
    name="Equal",
    full_name="tfcc.runtime.operations.relation.Equal",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _EQUAL_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=122,
)


_LESS = _descriptor.Descriptor(
    name="Less",
    full_name="tfcc.runtime.operations.relation.Less",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _LESS_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=124,
    serialized_end=163,
)


_LESSOREQUAL = _descriptor.Descriptor(
    name="LessOrEqual",
    full_name="tfcc.runtime.operations.relation.LessOrEqual",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _LESSOREQUAL_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=165,
    serialized_end=211,
)


_GREATER = _descriptor.Descriptor(
    name="Greater",
    full_name="tfcc.runtime.operations.relation.Greater",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _GREATER_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=213,
    serialized_end=255,
)


_GREATEROREQUAL = _descriptor.Descriptor(
    name="GreaterOrEqual",
    full_name="tfcc.runtime.operations.relation.GreaterOrEqual",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _GREATEROREQUAL_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=257,
    serialized_end=306,
)


_NOT = _descriptor.Descriptor(
    name="Not",
    full_name="tfcc.runtime.operations.relation.Not",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _NOT_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=308,
    serialized_end=346,
)


_UNEQUAL = _descriptor.Descriptor(
    name="UnEqual",
    full_name="tfcc.runtime.operations.relation.UnEqual",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _UNEQUAL_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=348,
    serialized_end=390,
)

_EQUAL_VERSION.containing_type = _EQUAL
_LESS_VERSION.containing_type = _LESS
_LESSOREQUAL_VERSION.containing_type = _LESSOREQUAL
_GREATER_VERSION.containing_type = _GREATER
_GREATEROREQUAL_VERSION.containing_type = _GREATEROREQUAL
_NOT_VERSION.containing_type = _NOT
_UNEQUAL_VERSION.containing_type = _UNEQUAL
DESCRIPTOR.message_types_by_name["Equal"] = _EQUAL
DESCRIPTOR.message_types_by_name["Less"] = _LESS
DESCRIPTOR.message_types_by_name["LessOrEqual"] = _LESSOREQUAL
DESCRIPTOR.message_types_by_name["Greater"] = _GREATER
DESCRIPTOR.message_types_by_name["GreaterOrEqual"] = _GREATEROREQUAL
DESCRIPTOR.message_types_by_name["Not"] = _NOT
DESCRIPTOR.message_types_by_name["UnEqual"] = _UNEQUAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Equal = _reflection.GeneratedProtocolMessageType(
    "Equal",
    (_message.Message,),
    dict(
        DESCRIPTOR=_EQUAL,
        __module__="tfcc_runtime.proto.operations.relation_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.relation.Equal)
    ),
)
_sym_db.RegisterMessage(Equal)

Less = _reflection.GeneratedProtocolMessageType(
    "Less",
    (_message.Message,),
    dict(
        DESCRIPTOR=_LESS,
        __module__="tfcc_runtime.proto.operations.relation_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.relation.Less)
    ),
)
_sym_db.RegisterMessage(Less)

LessOrEqual = _reflection.GeneratedProtocolMessageType(
    "LessOrEqual",
    (_message.Message,),
    dict(
        DESCRIPTOR=_LESSOREQUAL,
        __module__="tfcc_runtime.proto.operations.relation_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.relation.LessOrEqual)
    ),
)
_sym_db.RegisterMessage(LessOrEqual)

Greater = _reflection.GeneratedProtocolMessageType(
    "Greater",
    (_message.Message,),
    dict(
        DESCRIPTOR=_GREATER,
        __module__="tfcc_runtime.proto.operations.relation_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.relation.Greater)
    ),
)
_sym_db.RegisterMessage(Greater)

GreaterOrEqual = _reflection.GeneratedProtocolMessageType(
    "GreaterOrEqual",
    (_message.Message,),
    dict(
        DESCRIPTOR=_GREATEROREQUAL,
        __module__="tfcc_runtime.proto.operations.relation_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.relation.GreaterOrEqual)
    ),
)
_sym_db.RegisterMessage(GreaterOrEqual)

Not = _reflection.GeneratedProtocolMessageType(
    "Not",
    (_message.Message,),
    dict(
        DESCRIPTOR=_NOT,
        __module__="tfcc_runtime.proto.operations.relation_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.relation.Not)
    ),
)
_sym_db.RegisterMessage(Not)

UnEqual = _reflection.GeneratedProtocolMessageType(
    "UnEqual",
    (_message.Message,),
    dict(
        DESCRIPTOR=_UNEQUAL,
        __module__="tfcc_runtime.proto.operations.relation_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.relation.UnEqual)
    ),
)
_sym_db.RegisterMessage(UnEqual)


# @@protoc_insertion_point(module_scope)
