# Copyright 2021 Wechat Group, Tencent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfcc_runtime/proto/operations/rnn.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="tfcc_runtime/proto/operations/rnn.proto",
    package="tfcc.runtime.operations.rnn",
    syntax="proto3",
    serialized_pb=_b(
        '\n\'tfcc_runtime/proto/operations/rnn.proto\x12\x1btfcc.runtime.operations.rnn"I\n\x11\x42idirectionalLSTM\x12\x13\n\x0bhidden_size\x18\x01 \x01(\r"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01\x62\x06proto3'
    ),
)


_BIDIRECTIONALLSTM_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.rnn.BidirectionalLSTM.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=114,
    serialized_end=145,
)
_sym_db.RegisterEnumDescriptor(_BIDIRECTIONALLSTM_VERSION)


_BIDIRECTIONALLSTM = _descriptor.Descriptor(
    name="BidirectionalLSTM",
    full_name="tfcc.runtime.operations.rnn.BidirectionalLSTM",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="hidden_size",
            full_name="tfcc.runtime.operations.rnn.BidirectionalLSTM.hidden_size",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _BIDIRECTIONALLSTM_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=72,
    serialized_end=145,
)

_BIDIRECTIONALLSTM_VERSION.containing_type = _BIDIRECTIONALLSTM
DESCRIPTOR.message_types_by_name["BidirectionalLSTM"] = _BIDIRECTIONALLSTM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BidirectionalLSTM = _reflection.GeneratedProtocolMessageType(
    "BidirectionalLSTM",
    (_message.Message,),
    dict(
        DESCRIPTOR=_BIDIRECTIONALLSTM,
        __module__="tfcc_runtime.proto.operations.rnn_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.rnn.BidirectionalLSTM)
    ),
)
_sym_db.RegisterMessage(BidirectionalLSTM)


# @@protoc_insertion_point(module_scope)
