# Copyright 2021 Wechat Group, Tencent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfcc_runtime/proto/operations/signal.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="tfcc_runtime/proto/operations/signal.proto",
    package="tfcc.runtime.operations.signal",
    syntax="proto3",
    serialized_pb=_b(
        '\n*tfcc_runtime/proto/operations/signal.proto\x12\x1etfcc.runtime.operations.signal"7\n\x04RFFT\x12\x0e\n\x06length\x18\x01 \x01(\r"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01"8\n\x05IRFFT\x12\x0e\n\x06length\x18\x01 \x01(\r"\x1f\n\x07VERSION\x12\x05\n\x01_\x10\x00\x12\r\n\tVERSION_1\x10\x01\x62\x06proto3'
    ),
)


_RFFT_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.signal.RFFT.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=102,
    serialized_end=133,
)
_sym_db.RegisterEnumDescriptor(_RFFT_VERSION)

_IRFFT_VERSION = _descriptor.EnumDescriptor(
    name="VERSION",
    full_name="tfcc.runtime.operations.signal.IRFFT.VERSION",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="_", index=0, number=0, options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="VERSION_1", index=1, number=1, options=None, type=None
        ),
    ],
    containing_type=None,
    options=None,
    serialized_start=102,
    serialized_end=133,
)
_sym_db.RegisterEnumDescriptor(_IRFFT_VERSION)


_RFFT = _descriptor.Descriptor(
    name="RFFT",
    full_name="tfcc.runtime.operations.signal.RFFT",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="length",
            full_name="tfcc.runtime.operations.signal.RFFT.length",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _RFFT_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=78,
    serialized_end=133,
)


_IRFFT = _descriptor.Descriptor(
    name="IRFFT",
    full_name="tfcc.runtime.operations.signal.IRFFT",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="length",
            full_name="tfcc.runtime.operations.signal.IRFFT.length",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _IRFFT_VERSION,
    ],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=135,
    serialized_end=191,
)

_RFFT_VERSION.containing_type = _RFFT
_IRFFT_VERSION.containing_type = _IRFFT
DESCRIPTOR.message_types_by_name["RFFT"] = _RFFT
DESCRIPTOR.message_types_by_name["IRFFT"] = _IRFFT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RFFT = _reflection.GeneratedProtocolMessageType(
    "RFFT",
    (_message.Message,),
    dict(
        DESCRIPTOR=_RFFT,
        __module__="tfcc_runtime.proto.operations.signal_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.signal.RFFT)
    ),
)
_sym_db.RegisterMessage(RFFT)

IRFFT = _reflection.GeneratedProtocolMessageType(
    "IRFFT",
    (_message.Message,),
    dict(
        DESCRIPTOR=_IRFFT,
        __module__="tfcc_runtime.proto.operations.signal_pb2"
        # @@protoc_insertion_point(class_scope:tfcc.runtime.operations.signal.IRFFT)
    ),
)
_sym_db.RegisterMessage(IRFFT)


# @@protoc_insertion_point(module_scope)
